gui:
  language: en
  scrollHeight: 2
  scrollPastBottom: false
  sidePanelWidth: 0.2
  expandFocusedSidePanel: true
  showFileTree: true
  nerdFontsVersion: "3"
  showFileIcons: true
  border: Rounded
  animateDismissal: false
  filterMode: fuzzy
  statusPanelView: allBranchesLog
  showBranchCommitHash: true
  showDivergenceFromBaseBranch: arrowAndNumber
  mainPanelSplitMode: flexible
  timeFormat: "02 Jan 06"
  shortTimeFormat: "3:04PM"
  mouseEvents: true
  theme:
  activeBorderColor: ["#dc09b9", "bold"]
  inactiveBorderColor: ["#776262"]
  searchingActiveBorderColor: ["#dc073f", "bold"]
  optionsTextColor: ["#dc09b9"]
  selectedLineBgColor: ["#401310"]
  cherryPickedCommitFgColor: ["#dc09b9"]
  cherryPickedCommitBgColor: ["#776262"]
  unstagedChangesColor: ["#dc7202"]
  defaultFgColor: ["#e6cfcd"]
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side --line-numbers --syntax-theme="TwoDark"
os:
  editPreset: "nvim"
