gui:
  language: en
  scrollHeight: 2
  scrollPastBottom: false
  sidePanelWidth: 0.2
  expandFocusedSidePanel: true
  showFileTree: true
  nerdFontsVersion: "3"
  showFileIcons: true
  border: Rounded
  animateDismissal: false
  filterMode: fuzzy
  statusPanelView: allBranchesLog
  showBranchCommitHash: true
  showDivergenceFromBaseBranch: arrowAndNumber
  mainPanelSplitMode: flexible
  timeFormat: "02 Jan 06"
  shortTimeFormat: "3:04PM"
  mouseEvents: true
  theme:
  activeBorderColor: ["#dc9a09", "bold"]
  inactiveBorderColor: ["#64676B"]
  searchingActiveBorderColor: ["#dc0ac2", "bold"]
  optionsTextColor: ["#dc9a09"]
  selectedLineBgColor: ["#342728"]
  cherryPickedCommitFgColor: ["#dc9a09"]
  cherryPickedCommitBgColor: ["#64676B"]
  unstagedChangesColor: ["#4ddc08"]
  defaultFgColor: ["#dddfe6"]
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side --line-numbers --syntax-theme="TwoDark"
os:
  editPreset: "nvim"
