vim.g.mapleader = " "
vim.g.maplocalleader = " "

-- Bootstrap packages
vim.pack.add({ { src = "https://github.com/nvim-lua/plenary.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-tree/nvim-web-devicons" } }, { load = true })
vim.pack.add({ { src = "https://github.com/echasnovski/mini.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-treesitter/nvim-treesitter" } }, { load = true })
vim.pack.add({ { src = "https://github.com/shaunsingh/nord.nvim" } }, { load = true })
vim.o.cmdheight = 0
vim.pack.add({ { src = "https://github.com/mason-org/mason.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/mason-org/mason-lspconfig.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/stevearc/conform.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/christoomey/vim-tmux-navigator" } }, { load = true })
vim.pack.add({ "https://github.com/saghen/blink.lib", "https://github.com/saghen/blink.cmp" })
local cmp = require("blink.cmp")
cmp.build():pwait()
vim.pack.add({ { src = "https://github.com/rafamadriz/friendly-snippets" } }, { load = true })
vim.pack.add({ { src = "https://github.com/jiaoshijie/undotree" } }, { load = true })
vim.pack.add({ { src = "https://github.com/ibhagwan/fzf-lua" } }, { load = true })
vim.pack.add({ { src = "https://github.com/ThePrimeagen/harpoon", version = "harpoon2" } }, { load = true })
vim.pack.add({ { src = "https://github.com/lukas-reineke/indent-blankline.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/folke/which-key.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvimdev/dashboard-nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/mg979/vim-visual-multi" } }, { load = true })
vim.pack.add({ { src = "https://github.com/mikavilpas/yazi.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/MunifTanjim/nui.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-neo-tree/neo-tree.nvim" } }, { load = true })

-- Required Modules
require("modules.options")
require("modules.appearance")
require("modules.mini")
require("modules.statusline")
require("modules.dashboard")
require("modules.plugins")
require("modules.harpoon")
require("modules.blink")
require("modules.lang")
require("modules.keymaps")
require("modules.autocmds")
