-- Generated by matugen — do not edit manually
return {
  bg         = "#0a0f0c",
  bg_mid     = "#171d19",
  fg         = "#dfe4dd",
  fg_muted   = "#8a938b",
  normal     = "#92d5ac",
  on_normal  = "#003921",
  insert     = "#b5ccbb",
  on_insert  = "#213528",
  visual     = "#ffb4ab",
  on_visual  = "#690005",
  replace    = "#a3cddc",
  on_replace = "#043541",
  command    = "#055232",
  on_command = "#adf2c7",
  icon       = "#b5ccbb",
  shortcut   = "#ffb4ab",
  -- syntax overrides
  keyword    = "#92d5ac",
  str        = "#b5ccbb",
  func       = "#a3cddc",
  comment    = "#8a938b",
}
