local colors = require("colors")
require("modules.display")
require("modules.programs")
require("modules.permissions")
require("modules.input")
require("modules.keybinds")
require("modules.windowrule")
require("modules.workspace")
require("modules.decorations")
require("modules.autostart")
