-- Generated by theme-switcher -- tentacles.png
-- Do not edit manually. Edit theme-switcher-hyprland.sh:generate_hyprland instead.
hl.config({
	general = {
		col = {
			active_border = "rgba(0a5edcff)",
			inactive_border = "rgba(311A1Dff)",
		},
	},
})
