-- Generated by theme-switcher -- masks.png
-- Do not edit manually. Edit theme-switcher-hyprland.sh:generate_hyprland instead.
hl.config({
	general = {
		col = {
			active_border = "rgba(dc3e07ff)",
			inactive_border = "rgba(2B1512ff)",
		},
	},
})
