-- Generated by theme-switcher -- japan-green.png
-- Do not edit manually. Edit theme-switcher-hyprland.sh:generate_hyprland instead.
hl.config({
	general = {
		col = {
			active_border = "rgba(05dcb1ff)",
			inactive_border = "rgba(000205ff)",
		},
	},
})
